[package]
name = "rust-cli-todo"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] } # CLI parsing
serde = { version = "1.0", features = ["derive"] } # Serialization
serde_json = "1.0" # JSON support

[dev-dependencies]
tempfile = "3.10"